services:
  postgres-epaa:
    image: postgres:latest
    container_name: postgres_epaa_container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_epaa_data:/var/lib/postgresql/
      - ./postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    networks:
      - epaa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 131072
    mem_limit: 2g
    mem_reservation: 1g
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    shm_size: "1g"

volumes:
  postgres_epaa_data:
    name: postgres_epaa_data

networks:
  epaa-network:
    external: true
